### ISSUE TITLE
mobilenet caffe2onnx error

### ISSUE THREAD

**Issue by HappyKerry** [inisis/caffe2onnx#4]
Traceback (most recent call last):
  File "caffe2onnx.py", line 32, in <module>
    main()
  File "caffe2onnx.py", line 28, in main
    convert(args)
  File "caffe2onnx.py", line 21, in convert
    converter.run()
  File "/workspace/caffe2onnx-main/converter/onnx/caffe_parser.py", line 986, in run
    checker.check_model(self.model_def)
  File "/root/anaconda3/lib/python3.6/site-packages/onnx/checker.py", line 105, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Mismatched attribute type in 'relu1 : alpha'

==> Context: Bad node spec for node. Name: relu1 OpType: LeakyRelu

**Comment by inisis** [comment]
Can you provide your onnx && onnxruntime version
```
python 3.8
onnx                     1.11.0
onnxruntime              1.11.0
```
this works fine

**Comment by HappyKerry** [comment]
> Can you provide your onnx && onnxruntime version
> 
> ```
> python 3.8
> onnx                     1.11.0
> onnxruntime              1.11.0
> ```
> 
> this works fine

I reinstall caffe 
pip install brocolli-caffe==8.0.0 and it works
there might something wrong in the caffe build myself
