### ISSUE TITLE
Missing libprotobuf error

### ISSUE THREAD

**Issue by mikeklm** [inisis/caffe2onnx#5]
I have a caffe distribution that has all of the layers that are in your module.
I have succesfully bulit caffe and pycaffe for that build.
I set the CAFE_ROOT and PYTHONPATH variables to point to my build. 

When I run:
python caffe2onnx.py deploy.prototxtmodel_caffemodel onnx_name,
I get:
Traceback (most recent call last):
  File "caffe2onnx.py", line 3, in <module>
    from converter.onnx.caffe_parser import caffe2onnx_converter
  File "/home/mkraus/caffe2onnx/converter/onnx/caffe_parser.py", line 7, in <module>
    import caffe
  File "/home/mkraus/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/home/mkraus/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libprotobuf.so.9: cannot open shared object file: No such file or directory

If I don't set PYTHONPATH, I get a 'can't import caffe' error.

I tried running the model examples, these failed too. Please help

**Comment by inisis** [comment]
Hi, you can use this [caffe](https://github.com/inisis/caffe), or pip install brocolli-caffe

**Comment by mikeklm** [comment]
Do I need to have CAFFE_ROOT set to my caffe build, and do I need to have PYTHONPATH point to my pycaffe build?

If I create a new env, pip install your requirements.txt, and pip install brocolli-caffe, I get the error below. 

What does brocolli-caffe do? Can you just specify if I need to build caffe and pycaffe? If I do, I might know the problem

```
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xd . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
Traceback (most recent call last):
  File "caffe2onnx.py", line 3, in <module>
    from converter.onnx.caffe_parser import caffe2onnx_converter
  File "/home/mkraus/caffe2onnx_bk/converter/onnx/caffe_parser.py", line 7, in <module>
    import caffe
  File "/home/mkraus/.conda/envs/caffeconversion/lib/python3.8/site-packages/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/mkraus/.conda/envs/caffeconversion/lib/python3.8/site-packages/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
SystemError: initialization of _caffe raised unreported exception
```

**Comment by inisis** [comment]
You should set PYTHONPATH to your pycaffe build in order to use caffe, brocolli-caffe simplifies the installation in one line of code, in order to use brocolli-caffe, be aware of the numpy version, a typical version is 1.23.5, you can create a new conda env and install brocolli-caffe first

**Comment by mikeklm** [comment]
There must be something wrong with my caffe build, although it passes all the tests after I build it.
I'll try the build you pointed me to. 

I'm a little confused about your numpy statement. You explicitly list the numpy version to use as 1.19.5 in your requirement.txt file. But here you are saying it needs to be a later version, 1.23.5 ?

**Comment by inisis** [comment]
it maybe outdated, you should check the numpy version once caffe is built and keep it
